import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:image_picker/image_picker.dart';
import 'package:water_fountain_finder/providers/auth_provider.dart';
import 'package:water_fountain_finder/providers/fountain_provider.dart';
import 'package:water_fountain_finder/providers/location_provider.dart';
import 'package:water_fountain_finder/models/fountain.dart';
import 'package:water_fountain_finder/utils/constants.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class AddFountainScreen extends StatefulWidget {
  const AddFountainScreen({super.key});

  @override
  State<AddFountainScreen> createState() => _AddFountainScreenState();
}

class _AddFountainScreenState extends State<AddFountainScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _descriptionController = TextEditingController();
  
  FountainType _selectedType = FountainType.fountain;
  WaterQuality _selectedWaterQuality = WaterQuality.unknown;
  Accessibility _selectedAccessibility = Accessibility.public;
  final List<String> _selectedTags = [];
  final List<String> _photoUrls = [];
  
  bool _isLoading = false;
  bool _useCurrentLocation = true;
  double? _customLatitude;
  double? _customLongitude;

  final List<String> _availableTags = [
    '24h',
    'wheelchair_accessible',
    'cold_water',
    'hot_water',
    'filtered',
    'bottle_fill',
    'indoor',
    'outdoor',
    'parking_nearby',
    'restroom_nearby',
  ];

  @override
  void dispose() {
    _nameController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  Future<void> _pickImage() async {
    final ImagePicker picker = ImagePicker();
    final XFile? image = await picker.pickImage(
      source: ImageSource.camera,
      maxWidth: 1024,
      maxHeight: 1024,
      imageQuality: 80,
    );

    if (image != null) {
      // TODO: Upload image to Firebase Storage and get URL
      setState(() {
        _photoUrls.add('temp_url_${_photoUrls.length}');
      });
    }
  }

  Future<void> _pickImageFromGallery() async {
    final ImagePicker picker = ImagePicker();
    final XFile? image = await picker.pickImage(
      source: ImageSource.gallery,
      maxWidth: 1024,
      maxHeight: 1024,
      imageQuality: 80,
    );

    if (image != null) {
      // TODO: Upload image to Firebase Storage and get URL
      setState(() {
        _photoUrls.add('temp_url_${_photoUrls.length}');
      });
    }
  }

  void _removePhoto(int index) {
    setState(() {
      _photoUrls.removeAt(index);
    });
  }

  void _toggleTag(String tag) {
    setState(() {
      if (_selectedTags.contains(tag)) {
        _selectedTags.remove(tag);
      } else {
        _selectedTags.add(tag);
      }
    });
  }

  Future<void> _submitFountain() async {
    if (!_formKey.currentState!.validate()) return;

    final authProvider = Provider.of<AuthProvider>(context, listen: false);
    if (!authProvider.isAuthenticated) {
      _showAuthenticationDialog();
      return;
    }

    setState(() {
      _isLoading = true;
    });

    try {
      final locationProvider = Provider.of<LocationProvider>(context, listen: false);
      double latitude, longitude;

      if (_useCurrentLocation) {
        final position = await locationProvider.getCurrentLocation();
        if (position == null) {
          throw Exception('Unable to get current location');
        }
        latitude = position.latitude;
        longitude = position.longitude;
      } else {
        if (_customLatitude == null || _customLongitude == null) {
          throw Exception('Please enter custom coordinates');
        }
        latitude = _customLatitude!;
        longitude = _customLongitude!;
      }

      final fountain = Fountain(
        id: '', // Will be generated by Firestore
        name: _nameController.text.trim(),
        description: _descriptionController.text.trim(),
        location: GeoPoint(latitude, longitude),
        type: _selectedType,
        status: FountainStatus.active,
        waterQuality: _selectedWaterQuality,
        accessibility: _selectedAccessibility,
        addedBy: authProvider.currentUser!.uid,
        addedDate: DateTime.now(),
        validations: [],
        photos: _photoUrls,
        tags: _selectedTags,
      );

      final fountainProvider = Provider.of<FountainProvider>(context, listen: false);
      final success = await fountainProvider.addFountain(fountain);

      if (success && mounted) {
        _showSuccessDialog();
        _resetForm();
      } else {
        throw Exception('Failed to add fountain');
      }
    } catch (e) {
      if (mounted) {
        _showErrorDialog(e.toString());
      }
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  void _resetForm() {
    _formKey.currentState!.reset();
    _nameController.clear();
    _descriptionController.clear();
    setState(() {
      _selectedType = FountainType.fountain;
      _selectedWaterQuality = WaterQuality.unknown;
      _selectedAccessibility = Accessibility.public;
      _selectedTags.clear();
      _photoUrls.clear();
      _useCurrentLocation = true;
      _customLatitude = null;
      _customLongitude = null;
    });
  }

  void _showAuthenticationDialog() {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Authentication Required'),
        content: const Text(
          'You need to sign in to add new fountains. This helps us maintain data quality and track contributions.',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(),
            child: const Text('Cancel'),
          ),
          ElevatedButton(
            onPressed: () {
              Navigator.of(context).pop();
              // TODO: Navigate to sign in screen
            },
            child: const Text('Sign In'),
          ),
        ],
      ),
    );
  }

  void _showSuccessDialog() {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Success!'),
        content: const Text(
          'Your fountain has been added successfully! It will be reviewed by our community and should appear on the map soon.',
        ),
        actions: [
          ElevatedButton(
            onPressed: () => Navigator.of(context).pop(),
            child: const Text('Great!'),
          ),
        ],
      ),
    );
  }

  void _showErrorDialog(String error) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Error'),
        content: Text('Failed to add fountain: $error'),
        actions: [
          ElevatedButton(
            onPressed: () => Navigator.of(context).pop(),
            child: const Text('OK'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text(AppStrings.addFountain),
        backgroundColor: Colors.transparent,
        elevation: 0,
      ),
      body: Form(
        key: _formKey,
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(AppSizes.paddingM),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Basic Information
              _buildSectionTitle('Basic Information'),
              _buildTextField(
                controller: _nameController,
                label: 'Fountain Name',
                hint: 'e.g., Central Park Water Fountain',
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Please enter a fountain name';
                  }
                  return null;
                },
              ),
              const SizedBox(height: AppSizes.paddingM),
              _buildTextField(
                controller: _descriptionController,
                label: 'Description',
                hint: 'Describe the fountain, its location, or any special features...',
                maxLines: 3,
              ),

              const SizedBox(height: AppSizes.paddingL),

              // Fountain Type
              _buildSectionTitle('Fountain Type'),
              _buildDropdown<FountainType>(
                value: _selectedType,
                items: FountainType.values.map((type) {
                  return DropdownMenuItem(
                    value: type,
                    child: Text(type.name.toUpperCase()),
                  );
                }).toList(),
                onChanged: (value) {
                  setState(() {
                    _selectedType = value!;
                  });
                },
              ),

              const SizedBox(height: AppSizes.paddingM),

              // Water Quality
              _buildSectionTitle('Water Quality'),
              _buildDropdown<WaterQuality>(
                value: _selectedWaterQuality,
                items: WaterQuality.values.map((quality) {
                  return DropdownMenuItem(
                    value: quality,
                    child: Text(quality.name.toUpperCase()),
                  );
                }).toList(),
                onChanged: (value) {
                  setState(() {
                    _selectedWaterQuality = value!;
                  });
                },
              ),

              const SizedBox(height: AppSizes.paddingM),

              // Accessibility
              _buildSectionTitle('Accessibility'),
              _buildDropdown<Accessibility>(
                value: _selectedAccessibility,
                items: Accessibility.values.map((accessibility) {
                  return DropdownMenuItem(
                    value: accessibility,
                    child: Text(accessibility.name.toUpperCase()),
                  );
                }).toList(),
                onChanged: (value) {
                  setState(() {
                    _selectedAccessibility = value!;
                  });
                },
              ),

              const SizedBox(height: AppSizes.paddingL),

              // Location
              _buildSectionTitle('Location'),
              _buildLocationSection(),

              const SizedBox(height: AppSizes.paddingL),

              // Tags
              _buildSectionTitle('Tags'),
              _buildTagsSection(),

              const SizedBox(height: AppSizes.paddingL),

              // Photos
              _buildSectionTitle('Photos (Optional)'),
              _buildPhotosSection(),

              const SizedBox(height: AppSizes.paddingXL),

              // Submit Button
              SizedBox(
                width: double.infinity,
                child: ElevatedButton(
                  onPressed: _isLoading ? null : _submitFountain,
                  child: _isLoading
                      ? const SizedBox(
                          height: 20,
                          width: 20,
                          child: CircularProgressIndicator(strokeWidth: 2),
                        )
                      : const Text('Add Fountain'),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Padding(
      padding: const EdgeInsets.only(bottom: AppSizes.paddingS),
      child: Text(
        title,
        style: const TextStyle(
          fontSize: 18,
          fontWeight: FontWeight.w600,
          color: Colors.black87,
        ),
      ),
    );
  }

  Widget _buildTextField({
    required TextEditingController controller,
    required String label,
    required String hint,
    int maxLines = 1,
    String? Function(String?)? validator,
  }) {
    return TextFormField(
      controller: controller,
      maxLines: maxLines,
      decoration: InputDecoration(
        labelText: label,
        hintText: hint,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(AppSizes.radiusM),
        ),
        filled: true,
        fillColor: Colors.grey.shade50,
      ),
      validator: validator,
    );
  }

  Widget _buildDropdown<T>({
    required T value,
    required List<DropdownMenuItem<T>> items,
    required ValueChanged<T?> onChanged,
  }) {
    return DropdownButtonFormField<T>(
      value: value,
      items: items,
      onChanged: onChanged,
      decoration: InputDecoration(
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(AppSizes.radiusM),
        ),
        filled: true,
        fillColor: Colors.grey.shade50,
      ),
    );
  }

  Widget _buildLocationSection() {
    return Column(
      children: [
        // Location toggle
        Row(
          children: [
            Radio<bool>(
              value: true,
              groupValue: _useCurrentLocation,
              onChanged: (value) {
                setState(() {
                  _useCurrentLocation = value!;
                });
              },
            ),
            const Text('Use current location'),
            const Spacer(),
            Radio<bool>(
              value: false,
              groupValue: _useCurrentLocation,
              onChanged: (value) {
                setState(() {
                  _useCurrentLocation = value!;
                });
              },
            ),
            const Text('Enter coordinates'),
          ],
        ),

        if (!_useCurrentLocation) ...[
          const SizedBox(height: AppSizes.paddingM),
          Row(
            children: [
              Expanded(
                child: _buildTextField(
                  controller: TextEditingController(
                    text: _customLatitude?.toString() ?? '',
                  ),
                  label: 'Latitude',
                  hint: 'e.g., 40.7128',
                  validator: (value) {
                    if (value == null || value.isEmpty) {
                      return 'Please enter latitude';
                    }
                    final lat = double.tryParse(value);
                    if (lat == null || lat < -90 || lat > 90) {
                      return 'Invalid latitude';
                    }
                    _customLatitude = lat;
                    return null;
                  },
                ),
              ),
              const SizedBox(width: AppSizes.paddingM),
              Expanded(
                child: _buildTextField(
                  controller: TextEditingController(
                    text: _customLongitude?.toString() ?? '',
                  ),
                  label: 'Longitude',
                  hint: 'e.g., -74.0060',
                  validator: (value) {
                    if (value == null || value.isEmpty) {
                      return 'Please enter longitude';
                    }
                    final lon = double.tryParse(value);
                    if (lon == null || lon < -180 || lon > 180) {
                      return 'Invalid longitude';
                    }
                    _customLongitude = lon;
                    return null;
                  },
                ),
              ),
            ],
          ),
        ],
      ],
    );
  }

  Widget _buildTagsSection() {
    return Wrap(
      spacing: AppSizes.paddingS,
      runSpacing: AppSizes.paddingS,
      children: _availableTags.map((tag) {
        final isSelected = _selectedTags.contains(tag);
        return FilterChip(
          label: Text(tag.replaceAll('_', ' ')),
          selected: isSelected,
          onSelected: (selected) => _toggleTag(tag),
          selectedColor: AppColors.primary.withOpacity(0.2),
          checkmarkColor: AppColors.primary,
        );
      }).toList(),
    );
  }

  Widget _buildPhotosSection() {
    return Column(
      children: [
        Row(
          children: [
            Expanded(
              child: OutlinedButton.icon(
                onPressed: _pickImage,
                icon: const Icon(Icons.camera_alt),
                label: const Text('Take Photo'),
              ),
            ),
            const SizedBox(width: AppSizes.paddingM),
            Expanded(
              child: OutlinedButton.icon(
                onPressed: _pickImageFromGallery,
                icon: const Icon(Icons.photo_library),
                label: const Text('Choose Photo'),
              ),
            ),
          ],
        ),
        if (_photoUrls.isNotEmpty) ...[
          const SizedBox(height: AppSizes.paddingM),
          SizedBox(
            height: 100,
            child: ListView.builder(
              scrollDirection: Axis.horizontal,
              itemCount: _photoUrls.length,
              itemBuilder: (context, index) {
                return Container(
                  margin: const EdgeInsets.only(right: AppSizes.paddingS),
                  child: Stack(
                    children: [
                      Container(
                        width: 100,
                        height: 100,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(AppSizes.radiusM),
                          color: Colors.grey.shade200,
                        ),
                        child: const Icon(
                          Icons.image,
                          size: 40,
                          color: Colors.grey,
                        ),
                      ),
                      Positioned(
                        top: 4,
                        right: 4,
                        child: GestureDetector(
                          onTap: () => _removePhoto(index),
                          child: Container(
                            padding: const EdgeInsets.all(4),
                            decoration: const BoxDecoration(
                              color: Colors.red,
                              shape: BoxShape.circle,
                            ),
                            child: const Icon(
                              Icons.close,
                              size: 16,
                              color: Colors.white,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                );
              },
            ),
          ),
        ],
      ],
    );
  }
}
